colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableA11y = false
enableSearch = true
enableCodeCopy = false
enableStructuredBreadcrumbs = false
replyByEmail = false
disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
hotlinkFeatureImage = false
fingerprintAlgorithm = "sha512"
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v11.next.forgejo.org"
fathomAnalytics = { }
umamiAnalytics = { }
selineAnalytics = { }
buymeacoffee = { }
verification = { }
rssnext = { }
advertisement = { }

[header]
layout = "fixed-fill-blur"

[footer]
showMenu = true
showCopyright = false
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
showRecent = true
showRecentItems = 5
showMoreLink = false
showMoreLinkDest = "/posts/"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = false
disableHeroImageFilter = true
homepageImage = "eighty_six/4.jpg"

[article]
showDate = true
showViews = true
showLikes = true
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = true
showHero = true
heroStyle = "thumbAndBackground"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = true
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showCategories = true
showTags = true
showCategoriesInSecondaryColor = false
showAuthorsBadges = false
showWordCount = false
showZenMode = false

[list]
showHero = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showSummary = false
showViews = false
showLikes = false
showTableOfContents = false
showCards = false
orderByWeight = false
groupByYear = true
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = false

[term]
showHero = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false

[firebase] 
apiKey = "AIzaSyCPB64WoSc0otw32QWfYZo2l8hHnaSUhGI"
authDomain = "blog-blowfish-75af4.firebaseapp.com"
projectId = "blog-blowfish-75af4"
storageBucket = "blog-blowfish-75af4.firebasestorage.app"
messagingSenderId = "556021518657"
appId = "1:556021518657:web:03ecd46766935d22cf91c0"
measurementId = "G-DHHHRSJ47F" 